### PR TITLE
Update links.json with telegram link

### PR DESCRIPTION
**Pull request by SandroLinux**
Adds telegram link

### CODE REVIEW

**Comment by EnderDev** [comment]
Build failed.

**Comment by SandroLinux** [comment]
bruh

**Comment by SandroLinux** [comment]
oh shoot did not know that would break the preview

**Comment by SandroLinux** [comment]
fixed it I think

**Comment by SandroLinux** [comment]
silly me forgetting commas

**Comment by SandroLinux** [comment]
It now works @EnderDev

**Comment by SandroLinux** [comment]
ok thanks for merging it

**Pull request merged**
